### ISSUE TITLE
[remark-embedder] Twitter embed with double underscore doesn't work

### ISSUE THREAD

**Issue by MichaelDeBoey** [kentcdodds/old-kentcdodds.com#191]
When converting all of @CompuIves' [Medium posts](https://medium.com/@CompuIves/latest) over to @codesandbox' blog, I copy-pasted the `remark-embedder`. (see codesandbox/codesandbox-client#2011)

When looking at all the pages I came across a bug with the Twitter embed when the username contains 2 underscores (`_`).

When I try to embed the following Tweet, I just see the link with an italic `d` instead of the Tweet card itself:

```md
https://twitter.com/brian_d_vaughn/status/901488766581227520
```

An example can be seen at https://pr2011.build.csb.dev/post/creating-a-parallel-offline-extensible-browser-based-bundler-for-codesandbox

**Comment by kentcdodds** [comment]
Dang. Sounds like a bug in MDX I think... Could you open a bug there?

**Comment by kentcdodds** [comment]
Considering there's not much I can do here, I'll go ahead and close this one.

**Comment by MichaelDeBoey** [comment]
@kentcdodds @codesandbox isn't using MDX for it's blog/documentation, it's using `gatsby-transformer-remark` instead

**Comment by kentcdodds** [comment]
Could be a remark bug then because MDX is built on top of [remark](https://github.com/remarkjs/remark).

Actually, based on [this](https://astexplorer.net/#/gist/0a92bbf654aca4fdfb3f139254cf0bad/66eeb619b71beda9f2cbf6b15a2273d8e6496881) I'm pretty sure it's a plugin that's causing this issue because remark itself doesn't seem to have this problem.

Ok, I'll dig in really quick and see if it's my plugin first and let you know. Unfortunately I don't have the bandwidth to dig much deeper though.

**Comment by kentcdodds** [comment]
Ah, must be a problem in your setup because it works fine on my site:

![image](https://user-images.githubusercontent.com/1500684/58976572-01ac9b00-8785-11e9-81aa-06da2e90047c.png)

Sorry 😬

**Comment by MichaelDeBoey** [comment]
Hmmm no prob, will take a closer look at it myself then 🙂

Much appreciate the help tho! 👊
