### ISSUE TITLE
Update notification about some app

### ISSUE THREAD

**Issue by hudochenkov** [kentcdodds/old-kentcdodds.com#393]
Recently every time I visit your blog (every few days) I see this notification:

<img width="984" alt="Screen Shot 2020-02-25 at 20 00 08" src="https://user-images.githubusercontent.com/654597/75278437-27de0380-580a-11ea-9b39-54870362b333.png">

It confuses me, because I visit a static website and I didn't install any apps.

Could you consider hiding it, please?

P. S. Thank you for all the work you're doing. I learn a lot from you. And your “Testing JavaScript” course is a tremendous help establishing good testing habits in my company. (I convinced my employer to buy licenses to all our front-enders (after I bought my personal back in the days)).

**Comment by kentcdodds** [comment]
Hi @hudochenkov,

Actually, https://kentcdodds.com is an app using a [ServiceWorker](https://developers.google.com/web/fundamentals/primers/service-workers) and it's automatically downloaded and installed when you visit it. This allows the app to subsequently load VERY quickly (and it even works offline!).

But if there's been an update to the site, then you could be looking at old info.

I'm going to leave this open though because I want to see whether there's a way to only show the message if the page you're looking at was updated. Right now it shows up if *any* page was changed.

**Comment by hudochenkov** [comment]
Thank you for the quick reply!

It make sense. What about changing the text to be less confusing for folks like me? E. g.

> You're looking at the outdated page. Click here to display the latest version.

**Comment by charliewilco** [comment]
maybe a different UI pattern could give us this update info a little better https://material.io/components/snackbars/#usage

**Comment by kentcdodds** [comment]
This was removed because it was annoying. The whole service worker was removed because it was confusing.
