### ISSUE TITLE
Fix rss feed

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/old-kentcdodds.com#51]
Here's the code that used to be there: https://github.com/kentcdodds/kentcdodds.com/commit/de5dd06913d070732186a048e1b466ff730366c2

Waiting on (or need to contribute a fix to) this: https://github.com/ChristopherBiscardi/gatsby-mdx/issues/295

**Comment by z0al** [comment]
After many attempts, I've limited the number of feeds to 25 items only. I think is actually more [practical limit](https://github.com/z0al/kentcdodds.com/blob/495951a91a79b9ed9a2a8674039d855e393a00bf/gatsby-config.js#L145-L147) than 1000. The local build now works fine (will fail if you set the limit to +30).

But now I've other issues :disappointed: 

1) First I can't get the site to work on Netlify.com, the build takes ages and just stops here:

**Edit**: removed the log since it's clearly useless.

2) Also, the `<content:encoded>` tag is always empty now and I couldn't figure out why!!!:

https://github.com/z0al/kentcdodds.com/blob/495951a91a79b9ed9a2a8674039d855e393a00bf/gatsby-config.js#L163

Is there is something I'm not aware of?

**Comment by z0al** [comment]
Ok. After more than 25 mins, the build failed with this:

```
9:10:51 PM: Error: ENOSPC: System limit for number of file watchers reached, watch '/opt/build/repo/public/uses'
9:10:51 PM:     at FSWatcher.start (internal/fs/watchers.js:165:26)
9:10:51 PM:     at Object.watch (fs.js:1253:11)
9:10:51 PM:     at NodeWatcher.watchdir (/opt/build/repo/node_modules/sane/src/node_watcher.js:159:22)
9:10:51 PM:     at NodeWatcher.<anonymous> (/opt/build/repo/node_modules/sane/src/node_watcher.js:295:18)
9:10:51 PM:     at /opt/build/repo/node_modules/graceful-fs/polyfills.js:285:20
9:10:51 PM:     at FSReqWrap.oncomplete (fs.js:154:5)
9:10:51 PM: npm ERR! code ELIFECYCLE
9:10:51 PM: npm ERR! errno 1
9:10:51 PM: npm
9:10:51 PM: ERR!
9:10:51 PM:  kentcdodds.com@1.0.0 test:watch: `jest --watch`
```

**Comment by kentcdodds** [comment]
Thanks for working on it @z0al!

I'm fine with a limit of the latest 25 posts. But I still think that I'd like to fix perf issues because I don't want my blog deploys to take even longer than they already do. I think the real solution is figuring out how to optimize gatsby-mdx and not spawning a webpack build for every blog post to generate the RSS feed.

**Comment by z0al** [comment]
> I think the real solution is figuring out how to optimize gatsby-mdx and not spawning a webpack build for every blog post to generate the RSS feed.

Agree. But I thought this would be a temporary fix since I really needed the RSS feeds.

Sorry, don't have the time to dig in this, gonna leave it for someone else.

**Comment by kentcdodds** [comment]
Gotcha. Sorry, I'm not going to enable the RSS feed if it adds so much time to my build :-(
